# Generated by Django 6.1.1 on 2026-09-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, default='', max_length=100)),
                ('source_category', models.CharField(blank=True, default='', max_length=255)),
                ('source_sub_category', models.CharField(blank=True, default='', max_length=255)),
                ('brand_or_collection', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('bullets', models.TextField(blank=True, default='')),
                ('materials', models.CharField(blank=True, default='', max_length=500)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=200)),
                ('values', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(db_index=True, max_length=150, unique=True)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(db_index=True, max_length=500)),
                ('search_text', models.TextField(blank=True, default='')),
                ('attributes', models.ManyToManyField(blank=True, related_name='categories', to='classifier.taxonomyattribute')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='classifier.taxonomycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('alternative_categories', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('needs_review', models.BooleanField(db_index=True, default=True)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('approval_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('approved', 'Approved'), ('edited', 'Edited')], default='unreviewed', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='classifier.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='classifier.taxonomycategory')),
            ],
        ),
    ]
