# Generated by Django 6.1.1 on 2026-09-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], db_index=True, default="pending", max_length=20)),
                ("total_products", models.PositiveIntegerField(default=0)),
                ("processed_products", models.PositiveIntegerField(default=0)),
                ("classified_products", models.PositiveIntegerField(default=0)),
                ("failed_products", models.PositiveIntegerField(default=0)),
                ("needs_review_products", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="import_job",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="products", to="classifier.classificationjob"),
        ),
    ]
