# Generated by Django 6.1.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0002_classificationjob_product_import_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationjob",
            name="worker_lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classificationjob",
            name="worker_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
